export const REVIEW_STATUS_LABELS={pending_review:"Pending review",approved:"Approved",rejected_by_reviewer:"Rejected by reviewer"};
export const DUPLICATE_LABELS={new:"New record",already_exists:"Already exists",possible_duplicate:"Possible duplicate",not_checked:"Database match not checked"};
export const REJECTION_REASONS=["Not relevant to GHUS sectors","Not an organisation / event / person page","Duplicate of an existing record","Outside target geography","Past event with no useful participants","Insufficient evidence on the page","Other"];

export function reviewStatusLabel(value){return REVIEW_STATUS_LABELS[value]||String(value||"").replaceAll("_"," ");}
const DISCOVERY_UUID=/(?:discovery:)?[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/gi;
export function reviewRunLabel(source={}){
  const raw=String(source.description||source.source_description||"").trim();
  const cleaned=raw.replace(DISCOVERY_UUID,"").replace(/\s*·\s*(?=·|$)/g,"").replace(/[\s·:—-]+$/g,"").trim();
  if(cleaned&&!/^discovery$/i.test(cleaned))return cleaned;
  const entity=String(source.entity_type||"").trim().toLocaleLowerCase();
  return entity?`${entity.charAt(0).toLocaleUpperCase()+entity.slice(1)} discovery`:"Discovery run";
}
export function filterReviewCandidates(candidates,filters={}){
  const needle=String(filters.search||"").trim().toLocaleLowerCase();
  return (candidates||[]).filter(candidate=>{
    if(filters.status&&filters.status!=="all"&&candidate.status!==filters.status)return false;
    if(filters.entity_type&&filters.entity_type!=="all"&&candidate.entity_type!==filters.entity_type)return false;
    if(filters.source_run_id&&candidate.source_run_id!==filters.source_run_id)return false;
    return !needle||JSON.stringify([candidate.display_name,candidate.reviewed_payload]).toLocaleLowerCase().includes(needle);
  });
}
export function editableReviewPayload(candidate,draft){return Object.fromEntries((candidate?.editable_fields||[]).filter(field=>Object.prototype.hasOwnProperty.call(draft||{},field)).map(field=>[field,draft[field]]));}
export function decisionOptions(entityType){const noun={actor:"actor",event:"event",person:"person"}[entityType]||"record";return [{value:"same_existing",label:`Same as existing ${noun}`},{value:"new",label:`New ${noun}`},{value:"reject",label:"Reject"},{value:"defer",label:"Defer"}];}
export function validateReviewDraft(candidate,draft){
  const errors={};const payload=editableReviewPayload(candidate,draft);
  ["name",...(candidate?.entity_type==="person"?["affiliation","role"]:[])].forEach(field=>{if(!String(payload[field]??"").trim())errors[field]="Required.";});
  Object.entries(candidate?.field_constraints||{}).forEach(([field,rules])=>{if(rules?.max_length&&String(payload[field]??"").length>rules.max_length)errors[field]=`Maximum ${rules.max_length} characters.`;});
  return errors;
}
export function canSubmitReview({candidate,reviewer,rejectionReason,rejectionOther,decision,decisionKind,targetId,busy,admissionConfigured,draftErrors={}}){
  const kind=decisionKind||decision;if(!candidate||candidate.status!=="pending_review"||busy||!admissionConfigured||!String(reviewer||"").trim()||Object.keys(draftErrors).length)return false;
  if(kind==="same_existing"&&!String(targetId||"").trim())return false;
  if(kind==="reject")return REJECTION_REASONS.includes(rejectionReason)&&(rejectionReason!=="Other"||Boolean(String(rejectionOther||"").trim()));
  return ["same_existing","new","defer"].includes(kind);
}
export function diffFields(candidatePayload,match){const held=match?.payload||match||{};const keys=[...new Set([...Object.keys(candidatePayload||{}),...Object.keys(held)])].sort();return keys.filter(key=>JSON.stringify(candidatePayload?.[key]??null)!==JSON.stringify(held?.[key]??null)).map(key=>({field:key,candidate:candidatePayload?.[key]??null,existing:held?.[key]??null}));}

const REVIEW_FIELD_LABELS={actor_category:"Actor Category",category_type:"Category Type",category_note:"Category Note",actor_type:"Legacy Actor Type (compatibility)",actor_type_raw:"Original Type Evidence",location_city:"City",state:"State",region:"Region",country:"Country"};
export function reviewFieldLabel(field){return REVIEW_FIELD_LABELS[field]||field.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
export function lightPullFacts(candidate){return (candidate?.agent_metadata?.facts||[]).filter(fact=>fact?.fact_type==="light_pull"&&Number(fact?.layer)===1);}
export function deepPullFacts(candidate){return (candidate?.agent_metadata?.facts||[]).filter(fact=>fact?.fact_type==="deep_pull"&&Number(fact?.layer)===2);}
export function formatFactValue(value){if(value===null||value===undefined)return "No value recorded";if(typeof value==="string")return value;try{return JSON.stringify(value,null,2);}catch{return String(value);}}
function present(value){return value===null||value===undefined||String(value).trim()===""?null:String(value).trim();}
export function actorReviewSummary(payload={},originalPayload=payload){
  const legacyCategory=!present(originalPayload?.actor_category)&&present(originalPayload?.actor_type);
  return {
    actor_category:present(payload.actor_category)||present(payload.actor_type),
    category_type:present(payload.category_type),
    city:present(payload.location_city)||present(payload.city),
    state:present(payload.state),region:present(payload.region),country:present(payload.country),
    legacy_category_fallback:Boolean(legacyCategory),
  };
}

function decisionKey(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();return `review-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function errorMessage(body,status){const detail=body?.detail;if(typeof detail==="string")return detail;if(Array.isArray(detail))return detail.map(item=>item.msg).join(" ");if(detail?.message)return detail.message;return status===409?"This candidate was already decided.":"The review request failed.";}
async function request(url,options={}){const response=await fetch(url,options);let body={};try{body=await response.json();}catch{}if(!response.ok)throw new Error(errorMessage(body,response.status));return body;}
function fieldControl(html,candidate,field,value,onChange,disabled,error){const long=/description|activities|approach|summary|constraints|focus|research|category_note/.test(field);const type=field==="estimated_trl"?"number":/url|website/.test(field)?"url":"text";const limit=candidate?.field_constraints?.[field]?.max_length;return html`<label class=${"review-field "+(error?"invalid":"")}><span>${reviewFieldLabel(field)}</span>${long?html`<textarea rows="3" value=${value??""} maxlength=${limit} disabled=${disabled} onInput=${event=>onChange(field,event.target.value)}></textarea>`:html`<input type=${type} min=${type==="number"?1:undefined} max=${type==="number"?9:undefined} maxlength=${limit} value=${value??""} disabled=${disabled} onInput=${event=>onChange(field,event.target.value)}/>`}${error&&html`<small class="field-error">${error}</small>`}</label>`;}
function formatSync(lastSync){const row=(lastSync||[]).find(item=>item.source==="postgresql");return row?.last_success_at?new Date(row.last_success_at*1000).toLocaleString():"Not yet synchronized";}

export function createReviewPage({html,useEffect,useRef,useState}){
  return function Review(){
    const [filters,setFilters]=useState({status:"pending_review",entity_type:"all",source_run_id:"",search:""});
    const [data,setData]=useState({candidates:[],counts:{},source_maps:[],sync_warnings:[],last_sync:[],admission_configured:false});
    const [selectedId,setSelectedId]=useState(null),[selected,setSelected]=useState(null),[draft,setDraft]=useState({});
    const [reviewer,setReviewer]=useState(""),[notes,setNotes]=useState(""),[decisionKind,setDecisionKind]=useState("same_existing"),[targetId,setTargetId]=useState("");
    const [rejectionReason,setRejectionReason]=useState(""),[rejectionOther,setRejectionOther]=useState(""),[hubIds,setHubIds]=useState([]);
    const [proposeHub,setProposeHub]=useState(false),[proposedHub,setProposedHub]=useState({name:"",rationale:""});
    const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[feedback,setFeedback]=useState("");const keys=useRef(new Map());
    async function load(signal,force=false){setLoading(true);setError("");const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value&&value!=="all")params.set(key,value);});if(force)params.set("refresh","true");try{const next=await request(`/api/review/candidates?${params}`,{signal});setData(next);setSelectedId(current=>next.candidates.some(row=>row.candidate_id===current)?current:(next.candidates[0]?.candidate_id||null));}catch(exc){if(exc.name!=="AbortError")setError(exc.message);}finally{if(!signal?.aborted)setLoading(false);}}
    useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[filters.status,filters.entity_type,filters.source_run_id,filters.search]);
    useEffect(()=>{if(!selectedId){setSelected(null);setDraft({});return;}let active=true;request(`/api/review/candidates/${selectedId}`).then(candidate=>{if(!active)return;setSelected(candidate);setDraft({...candidate.reviewed_payload});setNotes(candidate.review_notes||"");const first=candidate.top_matches?.[0];setTargetId(first?.entity_id||first?.id||"");setDecisionKind(first?"same_existing":"new");setRejectionReason(candidate.rejection_reason||"");setHubIds([]);setProposeHub(false);setProposedHub({name:"",rationale:""});}).catch(exc=>{if(active)setError(exc.message);});return()=>{active=false;};},[selectedId]);
    function setFilter(key,value){setFilters(current=>({...current,[key]:value}));}function edit(field,value){setDraft(current=>({...current,[field]:value}));}
    async function save(){if(!selected||busy)return;setBusy(true);setError("");setFeedback("");try{const saved=await request(`/api/review/candidates/${selected.candidate_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fields:editableReviewPayload(selected,draft)})});setSelected(saved);setDraft({...saved.reviewed_payload});setFeedback("Review edits saved.");}catch(exc){setError(exc.message);}finally{setBusy(false);}}
    async function decide(){const draftErrors=validateReviewDraft(selected,draft);if(!canSubmitReview({candidate:selected,reviewer,rejectionReason,rejectionOther,decisionKind,targetId,busy,admissionConfigured:data.admission_configured,draftErrors}))return;if(!window.confirm(`Confirm ${decisionKind.replaceAll("_"," ")} for ${selected.display_name}?`))return;const keyName=`${selected.candidate_id}:${decisionKind}`;if(!keys.current.has(keyName))keys.current.set(keyName,decisionKey());const body={decision_kind:decisionKind,target_id:targetId||null,reviewer:reviewer.trim(),notes:notes.trim()||null,confirmed:true,idempotency_key:keys.current.get(keyName),edited_payload:editableReviewPayload(selected,draft),hub_ids:hubIds,proposed_hub:proposeHub?proposedHub:null,rejection_reason:decisionKind==="reject"?rejectionReason:null,rejection_reason_other:decisionKind==="reject"?rejectionOther.trim()||null:null};setBusy(true);setError("");setFeedback("");try{const decided=await request(`/api/review/candidates/${selected.candidate_id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});keys.current.delete(keyName);setSelected(decided);setFeedback("Decision committed to GHUS.");await load();}catch(exc){setError(exc.message);try{setSelected(await request(`/api/review/candidates/${selected.candidate_id}`));}catch{}}finally{setBusy(false);}}
    const counts=data.counts||{},pending=selected?.status==="pending_review",draftErrors=selected?validateReviewDraft(selected,draft):{},matches=selected?.top_matches||[],hubs=selected?.agent_metadata?.hubs||[],relationships=selected?.agent_metadata?.relationships||[],lightFacts=lightPullFacts(selected),deepFacts=deepPullFacts(selected),actorSummary=selected?.entity_type==="actor"?actorReviewSummary(draft,selected.original_payload):null;
    return html`<section class="review-page" aria-labelledby="review-title"><div class="eyebrow">Human admission control</div><h1 class="hero-h" id="review-title">Review agent discoveries.</h1><p class="lead">Compare evidence and matches, correct the final record, then commit one explicit decision.</p>
      <div class="review-counts" aria-label="Review queue counts">${["pending_review","approved","rejected_by_reviewer"].map(status=>html`<button key=${status} class=${"review-count "+(filters.status===status?"active":"")} onClick=${()=>setFilter("status",status)}><strong>${counts[status]||0}</strong><span>${reviewStatusLabel(status)}</span></button>`)}</div>
      <div class="review-sync"><span>Last PostgreSQL sync: ${formatSync(data.last_sync)}</span><button class="btn ghost" disabled=${loading} onClick=${()=>load(undefined,true)}>Refresh now</button></div>
      ${!data.admission_configured&&html`<div class="review-notice" role="status"><strong>Canonical admission is fail-closed.</strong> Apply the emitted migration and configure dedicated review-writer credentials to enable decisions.</div>`}${(data.sync_warnings||[]).map((warning,index)=>html`<div key=${index} class="review-message error" role="alert"><strong>Source sync warning:</strong> ${warning}</div>`)}
      <div class="review-filters" aria-label="Review filters"><label><span>Status</span><select value=${filters.status} onChange=${e=>setFilter("status",e.target.value)}><option value="pending_review">Pending review</option><option value="approved">Approved</option><option value="rejected_by_reviewer">Rejected</option><option value="all">All</option></select></label><label><span>Entity type</span><select value=${filters.entity_type} onChange=${e=>setFilter("entity_type",e.target.value)}><option value="all">All types</option><option value="actor">Actors</option><option value="person">People</option><option value="event">Events</option></select></label><label><span>Source run</span><select value=${filters.source_run_id} onChange=${e=>setFilter("source_run_id",e.target.value)}><option value="">All runs</option>${data.source_maps.map(map=>html`<option key=${map.source_run_id} value=${map.source_run_id}>${reviewRunLabel(map)}</option>`)}</select></label><label><span>Search</span><input type="search" value=${filters.search} onInput=${e=>setFilter("search",e.target.value)} placeholder="Name or field"/></label></div>
      ${error&&html`<div class="review-message error" role="alert">${error}</div>`}${feedback&&html`<div class="review-message success" role="status">${feedback}</div>`}
      <div class="review-workspace"><div class="review-queue" aria-label="Review candidates"><div class="review-queue-head"><strong>Candidate queue</strong><span>${data.candidates.length} shown</span></div>${loading&&html`<div class="review-empty" role="status">Loading candidates…</div>`}${!loading&&!data.candidates.length&&html`<div class="review-empty">No candidates match.</div>`}${data.candidates.map(candidate=>html`<button key=${candidate.candidate_id} class=${"review-row "+(selectedId===candidate.candidate_id?"active":"")} aria-pressed=${selectedId===candidate.candidate_id} onClick=${()=>setSelectedId(candidate.candidate_id)}><span class="review-row-main"><strong>${candidate.display_name}</strong><small>${candidate.entity_type} · ${reviewRunLabel(candidate)}</small></span><span class=${"review-status "+candidate.status}>${reviewStatusLabel(candidate.status)}</span></button>`)}</div>
      <article class="review-detail" aria-live="polite">${!selected&&html`<div class="review-empty">Select a candidate.</div>`}${selected&&html`<div class="review-detail-head"><div><span class="eyebrow">${selected.entity_type}</span><h2>${selected.display_name}</h2></div><div class="review-badges"><span class=${"review-status "+selected.status}>${reviewStatusLabel(selected.status)}</span><span class=${"duplicate-state "+selected.duplicate_state}>${DUPLICATE_LABELS[selected.duplicate_state]||selected.duplicate_state}</span></div></div>
        ${selected.admission_error&&html`<div class="review-message error"><strong>Last admission failed:</strong> ${selected.admission_error}</div>`}
        ${actorSummary&&html`<section class="review-section review-actor-summary"><h3>Actor classification and location</h3><div class="review-summary-group"><h4>Classification</h4><dl class="review-facts"><div><dt>Actor Category</dt><dd>${actorSummary.actor_category||"Not provided"}</dd></div><div><dt>Category Type</dt><dd>${actorSummary.category_type||"Not provided"}</dd></div></dl>${actorSummary.legacy_category_fallback&&html`<p class="review-compat-note">Actor Category is temporarily shown from the legacy actor_type field. Category Type is not inferred.</p>`}</div><div class="review-summary-group"><h4>Location</h4><dl class="review-facts"><div><dt>City</dt><dd>${actorSummary.city||"Not provided"}</dd></div><div><dt>State</dt><dd>${actorSummary.state||"Not provided"}</dd></div><div><dt>Region</dt><dd>${actorSummary.region||"Not provided"}</dd></div><div><dt>Country</dt><dd>${actorSummary.country||"Not provided"}</dd></div></dl></div></section>`}
        <section class="review-section"><h3>Final record</h3><div class="review-field-grid">${selected.editable_fields.map(field=>fieldControl(html,selected,field,draft[field],edit,!pending||busy,draftErrors[field]))}</div>${pending&&html`<button class="btn ghost" disabled=${busy||Object.keys(draftErrors).length>0} onClick=${save}>Save edits</button>`}</section>
        <section class="review-section"><h3>Evidence</h3>${!selected.evidence.length&&html`<p class="muted">No source links preserved.</p>`}<ul class="review-evidence">${selected.evidence.map((source,index)=>html`<li key=${source.url+index}><a href=${source.url} target="_blank" rel="noreferrer">${source.url}</a>${source.supports&&html`<span>${source.supports}</span>`}</li>`)}</ul></section>
        ${lightFacts.length>0&&html`<section class="review-section"><h3>Light Pull evidence</h3><p class="muted">Topic-scoped facts collected before this actor was parked. “Not found” means the evidence was absent from the pages read; it is not a claim that the fact does not exist.</p><ul class="review-evidence light-pull-facts">${lightFacts.map((fact,index)=>html`<li key=${fact.fact_key+index}><strong>${reviewFieldLabel(fact.fact_key)}</strong><span>${String(fact.collection_state||"not_yet_collected").replaceAll("_"," ")} · confidence ${fact.confidence||"not provided"}${fact.date_read?` · read ${new Date(fact.date_read).toLocaleDateString()}`:""}</span><pre>${formatFactValue(fact.value)}</pre>${fact.source_url&&html`<a href=${fact.source_url} target="_blank" rel="noreferrer">Source</a>`}</li>`)}</ul></section>`}
        ${deepFacts.length>0&&html`<section class="review-section"><h3>Verified Deep Pull evidence</h3><p class="muted">Selected topic-specific facts collected only after a GHUS verification decision.</p><ul class="review-evidence light-pull-facts">${deepFacts.map((fact,index)=>html`<li key=${fact.fact_key+index}><strong>${reviewFieldLabel(fact.fact_key)}</strong><span>${String(fact.collection_state||"not_yet_collected").replaceAll("_"," ")} · confidence ${fact.confidence||"not provided"}${fact.date_read?` · read ${new Date(fact.date_read).toLocaleDateString()}`:""}</span><pre>${formatFactValue(fact.value)}</pre>${fact.source_url&&html`<a href=${fact.source_url} target="_blank" rel="noreferrer">Source</a>`}</li>`)}</ul></section>`}
        ${relationships.length>0&&html`<section class="review-section"><h3>Sourced relationships</h3><ul class="review-evidence">${relationships.map((edge,index)=>html`<li key=${(edge.relationship_type||"")+index}><strong>${edge.relationship_type}</strong><span>${edge.direction} · ${edge.counterpart_type} · ${edge.counterpart_id} · confidence ${edge.confidence||"not provided"}</span>${edge.source_url&&html`<a href=${edge.source_url} target="_blank" rel="noreferrer">${edge.source_url}</a>`}</li>`)}</ul></section>`}
        <section class="review-section"><h3>Top existing matches and differences</h3>${!matches.length&&html`<p class="muted">No existing match was proposed.</p>`}${matches.map(match=>html`<div class="review-match" key=${match.entity_id||match.id}><label><input type="radio" name="target-match" checked=${targetId===(match.entity_id||match.id)} onChange=${()=>setTargetId(match.entity_id||match.id)}/>${match.name||match.display_name||match.entity_id||match.id}</label><table><tbody>${diffFields(draft,match).map(diff=>html`<tr key=${diff.field}><th>${diff.field}</th><td>${String(diff.candidate??"")}</td><td>${String(diff.existing??"")}</td></tr>`)}</tbody></table></div>`)}</section>
        <details class="review-section"><summary>Rubric evidence, score breakdown, qualification, and rerank</summary><pre>${JSON.stringify(selected.agent_metadata,null,2)}</pre></details><details class="review-section"><summary>Complete original discovery payload</summary><pre>${JSON.stringify(selected.original_payload,null,2)}</pre></details>
        <section class="review-section review-decision"><h3>Decision</h3><label class="review-field"><span>Decision</span><select value=${decisionKind} disabled=${!pending||busy} onChange=${e=>setDecisionKind(e.target.value)}>${decisionOptions(selected.entity_type).map(option=>html`<option value=${option.value}>${option.label}</option>`)}</select></label>${decisionKind==="same_existing"&&html`<label class="review-field"><span>Existing record ID</span><input value=${targetId} disabled=${!pending||busy} onInput=${e=>setTargetId(e.target.value)} required/></label>`}
          ${selected.entity_type==="actor"&&["same_existing","new"].includes(decisionKind)&&html`<div><label class="review-field"><span>Existing hubs</span><select multiple value=${hubIds} disabled=${!pending||busy} onChange=${e=>setHubIds([...e.target.selectedOptions].map(option=>option.value))}>${hubs.map(hub=>html`<option value=${hub.hub_id}>${hub.name}</option>`)}</select></label><label><input type="checkbox" checked=${proposeHub} onChange=${e=>setProposeHub(e.target.checked)}/> Propose a new hub</label>${proposeHub&&html`<div class="review-field-grid"><label class="review-field"><span>Proposed hub name</span><input value=${proposedHub.name} onInput=${e=>setProposedHub(current=>({...current,name:e.target.value}))}/></label><label class="review-field"><span>Rationale</span><textarea value=${proposedHub.rationale} onInput=${e=>setProposedHub(current=>({...current,rationale:e.target.value}))}></textarea></label></div>`}</div>`}
          ${decisionKind==="reject"&&html`<div><label class="review-field"><span>Rejection reason</span><select value=${rejectionReason} onChange=${e=>setRejectionReason(e.target.value)}><option value="">Select a reason</option>${REJECTION_REASONS.map(reason=>html`<option value=${reason}>${reason}</option>`)}</select></label>${rejectionReason==="Other"&&html`<label class="review-field"><span>Other reason</span><textarea value=${rejectionOther} onInput=${e=>setRejectionOther(e.target.value)} required></textarea></label>`}</div>`}
          <label class="review-field"><span>Reviewer</span><input value=${reviewer} disabled=${!pending||busy} onInput=${e=>setReviewer(e.target.value)} required/></label><label class="review-field"><span>Notes${decisionKind==="defer"?" (why it remains pending)":""}</span><textarea value=${notes} disabled=${!pending||busy} onInput=${e=>setNotes(e.target.value)}></textarea></label><button class=${"btn "+(decisionKind==="reject"?"danger":"")} disabled=${!canSubmitReview({candidate:selected,reviewer,rejectionReason,rejectionOther,decisionKind,targetId,busy,admissionConfigured:data.admission_configured,draftErrors})} onClick=${decide}>${busy?"Committing…":"Commit decision"}</button>
        </section>`}</article></div></section>`;
  };
}
