export const REVIEW_STATUS_LABELS={pending_review:"Pending review",approved:"Approved",rejected_by_reviewer:"Rejected by reviewer"};
export const DUPLICATE_LABELS={new:"New record",already_exists:"Already exists",possible_duplicate:"Possible duplicate",not_checked:"Database match not checked"};
export const REJECTION_REASONS=["Not relevant to GHUS sectors","Not an organisation / event / person page","Duplicate of an existing record","Outside target geography","Past event with no useful participants","Insufficient evidence on the page","Other"];

export function reviewStatusLabel(value){return REVIEW_STATUS_LABELS[value]||String(value||"").replaceAll("_"," ");}
export function reviewQueryParams(filters={},force=false){const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,value);});if(force)params.set("refresh","true");return params;}
const DISCOVERY_UUID=/(?:discovery:)?[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/gi;
export function reviewRunLabel(source={}){
  const labeled=String(source.run_label||source?.agent_metadata?.review_run_label||"").trim();
  if(labeled)return labeled;
  const raw=String(source.description||source.source_description||"").trim();
  const cleaned=raw.replace(DISCOVERY_UUID,"").replace(/\s*·\s*(?=·|$)/g,"").replace(/[\s·:—-]+$/g,"").trim();
  if(cleaned&&!/^discovery$/i.test(cleaned))return cleaned;
  const entity=String(source.entity_type||"").trim().toLocaleLowerCase();
  return entity?`${entity.charAt(0).toLocaleUpperCase()+entity.slice(1)} discovery`:"Discovery run";
}
export function filterReviewCandidates(candidates,filters={}){
  const needle=String(filters.search||"").trim().toLocaleLowerCase();
  return (candidates||[]).filter(candidate=>{
    if(filters.status&&filters.status!=="all"&&candidate.status!==filters.status)return false;
    if(filters.entity_type&&filters.entity_type!=="all"&&candidate.entity_type!==filters.entity_type)return false;
    if(filters.source_run_id&&candidate.source_run_id!==filters.source_run_id)return false;
    return !needle||JSON.stringify([candidate.display_name,candidate.reviewed_payload]).toLocaleLowerCase().includes(needle);
  });
}
export function editableReviewPayload(candidate,draft){return Object.fromEntries((candidate?.editable_fields||[]).filter(field=>Object.prototype.hasOwnProperty.call(draft||{},field)).map(field=>[field,draft[field]]));}
export function decisionOptions(entityType){const noun={actor:"actor",event:"event",person:"person"}[entityType]||"record";return [{value:"same_existing",label:`Same as existing ${noun}`},{value:"new",label:`New ${noun}`},{value:"reject",label:"Reject"},{value:"defer",label:"Defer"}];}
export function validateReviewDraft(candidate,draft){
  const errors={};const payload=editableReviewPayload(candidate,draft);
  ["name",...(candidate?.entity_type==="person"?["affiliation","role"]:[])].forEach(field=>{if(!String(payload[field]??"").trim())errors[field]="Required.";});
  Object.entries(candidate?.field_constraints||{}).forEach(([field,rules])=>{if(rules?.max_length&&String(payload[field]??"").length>rules.max_length)errors[field]=`Maximum ${rules.max_length} characters.`;});
  return errors;
}
export function canSubmitReview({candidate,reviewer,rejectionReason,rejectionOther,decision,decisionKind,targetId,busy,admissionConfigured,draftErrors={},manualHubOverride=false,notes=""}){
  const kind=decisionKind||decision;if(!candidate||candidate.status!=="pending_review"||busy||!admissionConfigured||!String(reviewer||"").trim()||Object.keys(draftErrors).length)return false;
  if(manualHubOverride&&!String(notes||"").trim())return false;
  if(kind==="same_existing"&&!String(targetId||"").trim())return false;
  if(kind==="reject")return REJECTION_REASONS.includes(rejectionReason)&&(rejectionReason!=="Other"||Boolean(String(rejectionOther||"").trim()));
  return ["same_existing","new","defer"].includes(kind);
}
export function diffFields(candidatePayload,match){const held=match?.payload||match||{},internal=new Set(["id","entity_id","actor_id","event_id","person_id"]);const keys=[...new Set([...Object.keys(candidatePayload||{}),...Object.keys(held)])].sort();return keys.filter(key=>!internal.has(key)&&JSON.stringify(candidatePayload?.[key]??null)!==JSON.stringify(held?.[key]??null)).map(key=>({field:key,candidate:candidatePayload?.[key]??null,existing:held?.[key]??null}));}

const REVIEW_FIELD_LABELS={actor_category:"Actor Category",category_type:"Category Type",category_note:"Category Note",actor_type:"Legacy Actor Type (compatibility)",actor_type_raw:"Original Type Evidence",location_city:"City",state:"State",region:"Region",country:"Country"};
export function reviewFieldLabel(field){return REVIEW_FIELD_LABELS[field]||field.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
export function lightPullFacts(candidate){return (candidate?.agent_metadata?.facts||[]).filter(fact=>fact?.fact_type==="light_pull"&&Number(fact?.layer)===1);}
export function deepPullFacts(candidate){return (candidate?.agent_metadata?.facts||[]).filter(fact=>fact?.fact_type==="deep_pull"&&Number(fact?.layer)===2);}
export function formatFactValue(value){if(value===null||value===undefined)return "No value recorded";if(typeof value==="string")return value;try{return JSON.stringify(value,null,2);}catch{return String(value);}}
function present(value){return value===null||value===undefined||String(value).trim()===""?null:String(value).trim();}
export function actorReviewSummary(payload={},originalPayload=payload){
  const legacyCategory=!present(originalPayload?.actor_category)&&present(originalPayload?.actor_type);
  return {
    actor_category:present(payload.actor_category)||present(payload.actor_type),
    category_type:present(payload.category_type),
    city:present(payload.location_city)||present(payload.city),
    state:present(payload.state),region:present(payload.region),country:present(payload.country),
    legacy_category_fallback:Boolean(legacyCategory),
  };
}

function optionalNumber(value){if(value===null||value===undefined||value==="")return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:null;}
function hubRecord(raw={}){return {
  ...raw,
  hub_id:String(raw.hub_id||raw.id||""),
  name:String(raw.name||raw.hub_name||""),
  topic_id:raw.topic_id||null,
  topic_name:raw.topic_name||raw.hub_topic_name||null,
  distance_miles:optionalNumber(raw.distance_miles),
  radius_miles:optionalNumber(raw.radius_miles),
};}
export function hubAssignmentState(assignment={}){
  const outcome=String(assignment.outcome||"").toLocaleLowerCase();
  const issue=String(assignment.review_kind||assignment.issue||"").toLocaleLowerCase();
  if(assignment.topic_match===false||outcome==="needs_review_topic")return "topic_mismatch";
  if(issue==="hub_radius_overlap"||outcome==="hub_radius_overlap"||outcome==="same_topic_overlap")return "overlap";
  if(assignment.location_evaluated===false||assignment.coordinates_available===false)return "missing_location";
  if(outcome==="needs_review_location"||assignment.within_radius===false)return "outside_radius";
  if(["assigned","recommended","eligible","auto_assigned"].includes(outcome)&&assignment.recommended_hub_id)return "recommended";
  return assignment.recommended_hub_id?"review":"unavailable";
}
export function hubAssignments(candidate={}){
  const source=candidate&&typeof candidate==="object"?candidate:{};
  const metadata=source.agent_metadata||{};
  const rows=Array.isArray(metadata.hub_assignments)?metadata.hub_assignments:Array.isArray(source.hub_assignments)?source.hub_assignments:[];
  return rows.filter(row=>row&&typeof row==="object").map((row,index)=>{
    const recommended=hubRecord(typeof row.recommended_hub==="object"?row.recommended_hub:{});
    const recommendedHubId=String(row.recommended_hub_id||recommended.hub_id||"");
    const recommendedHubName=String((typeof row.recommended_hub==="string"?row.recommended_hub:null)||row.recommended_hub_name||recommended.name||"");
    const normalized={
      ...row,
      key:String(row.topic_id||row.topic_name||`topic-${index}`),
      topic_id:row.topic_id||null,
      topic_name:String(row.topic_name||row.actor_topic_name||"Topic not provided"),
      hub_topic_name:String(row.hub_topic_name||recommended.topic_name||row.topic_name||"Topic not provided"),
      recommended_hub_id:recommendedHubId,
      recommended_hub_name:recommendedHubName,
      distance_miles:optionalNumber(row.distance_miles??recommended.distance_miles),
      radius_miles:optionalNumber(row.radius_miles??recommended.radius_miles),
      competing_hubs:(Array.isArray(row.competing_hubs)?row.competing_hubs:[]).map(hubRecord),
    };
    return {...normalized,state:hubAssignmentState(normalized)};
  });
}
export function existingHubMemberships(candidate={}){
  const source=candidate&&typeof candidate==="object"?candidate:{};
  const metadata=source.agent_metadata||{};
  const rows=metadata.existing_memberships||metadata.existing_hub_memberships||[];
  return (Array.isArray(rows)?rows:[]).filter(row=>row&&typeof row==="object").map(hubRecord);
}
export function hubProposalStatuses(candidate={}){
  const source=candidate&&typeof candidate==="object"?candidate:{};
  const metadata=source.agent_metadata||{};
  const rows=metadata.hub_proposal_memberships||metadata.hub_proposals||[];
  return (Array.isArray(rows)?rows:[]).filter(row=>row&&typeof row==="object");
}
export function manualHubOptions(catalog=[],assignment={},search=""){
  const needle=String(search||"").trim().toLocaleLowerCase();
  const actorTopic=String(assignment.topic_id||"");
  return (Array.isArray(catalog)?catalog:[]).map(hubRecord).filter(hub=>!needle||`${hub.name} ${hub.topic_name||""}`.toLocaleLowerCase().includes(needle)).sort((left,right)=>{
    const leftMatch=Boolean(actorTopic&&left.topic_id&&String(left.topic_id)===actorTopic);
    const rightMatch=Boolean(actorTopic&&right.topic_id&&String(right.topic_id)===actorTopic);
    if(leftMatch!==rightMatch)return leftMatch?-1:1;
    return left.name.localeCompare(right.name);
  });
}

function decisionKey(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();return `review-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function errorMessage(body,status){const detail=body?.detail;if(typeof detail==="string")return detail;if(Array.isArray(detail))return detail.map(item=>item.msg).join(" ");if(detail?.message)return detail.message;return status===409?"This candidate was already decided.":"The review request failed.";}
async function request(url,options={}){const response=await fetch(url,options);let body={};try{body=await response.json();}catch{}if(!response.ok)throw new Error(errorMessage(body,response.status));return body;}
function fieldControl(html,candidate,field,value,onChange,disabled,error){const long=/description|activities|approach|summary|constraints|focus|research|category_note/.test(field);const type=field==="estimated_trl"?"number":/url|website/.test(field)?"url":"text";const limit=candidate?.field_constraints?.[field]?.max_length;return html`<label class=${"review-field "+(error?"invalid":"")}><span>${reviewFieldLabel(field)}</span>${long?html`<textarea rows="3" value=${value??""} maxlength=${limit} disabled=${disabled} onInput=${event=>onChange(field,event.target.value)}></textarea>`:html`<input type=${type} min=${type==="number"?1:undefined} max=${type==="number"?9:undefined} maxlength=${limit} value=${value??""} disabled=${disabled} onInput=${event=>onChange(field,event.target.value)}/>`}${error&&html`<small class="field-error">${error}</small>`}</label>`;}
export function formatReviewTime(seconds){if(!Number.isFinite(Number(seconds)))return "Time unavailable";return new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZoneName:"short"}).format(new Date(Number(seconds)*1000)).replace(/, (?=\d{2}:)/," · ");}
export function formatReviewRefresh(lastSync){const row=(lastSync||[]).find(item=>item.source==="postgresql");return row?.last_success_at?formatReviewTime(row.last_success_at):"Not yet refreshed";}
export function latestRunOutcome(run={}){const parts=[];if(Number(run.records_staged))parts.push(`${run.records_staged} staged`);if(Number(run.queued_for_review))parts.push(`${run.queued_for_review} queued for review`);if(Number(run.records_promoted))parts.push(`${run.records_promoted} promoted`);if(Number(run.pending_review))parts.push(`${run.pending_review} pending now`);return parts.join(" · ")||"No review records produced";}

export function createReviewPage({html,useEffect,useRef,useState}){
  return function Review(){
    const [filters,setFilters]=useState({inbox:"current",status:"pending_review",entity_type:"all",source_run_id:"",search:""});
    const [data,setData]=useState({candidates:[],counts:{},source_maps:[],sync_warnings:[],last_sync:[],admission_configured:false});
    const [selectedId,setSelectedId]=useState(null),[selected,setSelected]=useState(null),[draft,setDraft]=useState({});
    const [reviewer,setReviewer]=useState(""),[notes,setNotes]=useState(""),[decisionKind,setDecisionKind]=useState("same_existing"),[targetId,setTargetId]=useState("");
    const [rejectionReason,setRejectionReason]=useState(""),[rejectionOther,setRejectionOther]=useState(""),[hubIds,setHubIds]=useState([]);
    const [hubSelections,setHubSelections]=useState({}),[manualTopicKey,setManualTopicKey]=useState(null),[hubSearch,setHubSearch]=useState("");
    const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[feedback,setFeedback]=useState("");const keys=useRef(new Map());
    async function load(signal,force=false){setLoading(true);setError("");const params=reviewQueryParams(filters,force);try{const next=await request(`/api/review/candidates?${params}`,{signal});setData(next);setSelectedId(current=>next.candidates.some(row=>row.candidate_id===current)?current:(next.candidates[0]?.candidate_id||null));}catch(exc){if(exc.name!=="AbortError")setError(exc.message);}finally{if(!signal?.aborted)setLoading(false);}}
    useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[filters.inbox,filters.status,filters.entity_type,filters.source_run_id,filters.search]);
    useEffect(()=>{if(!selectedId){setSelected(null);setDraft({});return;}let active=true;request(`/api/review/candidates/${selectedId}`).then(candidate=>{if(!active)return;setSelected(candidate);setDraft({...candidate.reviewed_payload});setNotes(candidate.review_notes||"");const first=candidate.top_matches?.[0];setTargetId(first?.entity_id||first?.id||"");setDecisionKind(first?"same_existing":"new");setRejectionReason(candidate.rejection_reason||"");setHubIds([]);setHubSelections({});setManualTopicKey(null);setHubSearch("");}).catch(exc=>{if(active)setError(exc.message);});return()=>{active=false;};},[selectedId]);
    function setFilter(key,value){setFilters(current=>({...current,[key]:value}));}function edit(field,value){setDraft(current=>({...current,[field]:value}));}
    async function save(){if(!selected||busy)return;setBusy(true);setError("");setFeedback("");try{const saved=await request(`/api/review/candidates/${selected.candidate_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fields:editableReviewPayload(selected,draft)})});setSelected(saved);setDraft({...saved.reviewed_payload});setFeedback("Review edits saved.");}catch(exc){setError(exc.message);}finally{setBusy(false);}}
    function chooseHub(topicKey,hubId,source){setHubSelections(current=>{const previous=current[topicKey]?.hub_id;setHubIds(ids=>[...new Set([...ids.filter(id=>id!==previous&&id!==hubId),...(hubId?[hubId]:[])])]);return {...current,[topicKey]:{hub_id:hubId,source}};});setManualTopicKey(null);setHubSearch("");}
    function leaveHubUnassigned(topicKey){setHubSelections(current=>{const previous=current[topicKey]?.hub_id;setHubIds(ids=>ids.filter(id=>id!==previous));return {...current,[topicKey]:{hub_id:"",source:"unassigned"}};});setManualTopicKey(null);setHubSearch("");}
    const manualHubOverride=Object.values(hubSelections).some(choice=>choice?.source==="manual");
    async function decide(){const draftErrors=validateReviewDraft(selected,draft);if(!canSubmitReview({candidate:selected,reviewer,rejectionReason,rejectionOther,decisionKind,targetId,busy,admissionConfigured:data.admission_configured,draftErrors,manualHubOverride,notes}))return;if(!window.confirm(`Confirm ${decisionKind.replaceAll("_"," ")} for ${selected.display_name}?`))return;const keyName=`${selected.candidate_id}:${decisionKind}`;if(!keys.current.has(keyName))keys.current.set(keyName,decisionKey());const body={decision_kind:decisionKind,target_id:targetId||null,reviewer:reviewer.trim(),notes:notes.trim()||null,confirmed:true,idempotency_key:keys.current.get(keyName),edited_payload:editableReviewPayload(selected,draft),hub_ids:hubIds,proposed_hub:null,rejection_reason:decisionKind==="reject"?rejectionReason:null,rejection_reason_other:decisionKind==="reject"?rejectionOther.trim()||null:null};setBusy(true);setError("");setFeedback("");try{const decided=await request(`/api/review/candidates/${selected.candidate_id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});keys.current.delete(keyName);setSelected(decided);setFeedback("Decision committed to GHUS.");await load();}catch(exc){setError(exc.message);try{setSelected(await request(`/api/review/candidates/${selected.candidate_id}`));}catch{}}finally{setBusy(false);}}
    const counts=data.counts||{},pending=selected?.status==="pending_review",draftErrors=selected?validateReviewDraft(selected,draft):{},matches=selected?.top_matches||[],hubCatalog=selected?.agent_metadata?.hubs||[],assignments=hubAssignments(selected),existingMemberships=existingHubMemberships(selected),proposalStatuses=hubProposalStatuses(selected),relationships=selected?.agent_metadata?.relationships||[],lightFacts=lightPullFacts(selected),deepFacts=deepPullFacts(selected),actorSummary=selected?.entity_type==="actor"?actorReviewSummary(draft,selected.original_payload):null;
    return html`<section class="review-page" aria-labelledby="review-title"><div class="eyebrow">Human admission control</div><h1 class="hero-h" id="review-title">Review agent discoveries.</h1><p class="lead">Compare evidence and matches, correct the final record, then commit one explicit decision.</p>
      <div class="review-counts" aria-label="Review queue counts">${["pending_review","approved","rejected_by_reviewer"].map(status=>html`<button key=${status} class=${"review-count "+(filters.status===status?"active":"")} onClick=${()=>setFilter("status",status)}><strong>${counts[status]||0}</strong><span>${reviewStatusLabel(status)}</span></button>`)}</div>
      ${(data.latest_runs||[]).length>0&&html`<section class="review-latest-runs" aria-label="Latest discovery runs"><div class="review-section-title"><span class="eyebrow">Latest discovery</span><strong>Real run status</strong></div><div class="review-run-grid">${data.latest_runs.map(run=>html`<article class=${"review-run-card "+run.status} key=${run.entity_type}><div><strong>${run.label}</strong><span class=${"review-run-status "+run.status}>${run.status_label}</span></div><time>${formatReviewTime(run.finished_at||run.started_at)}</time><p>${latestRunOutcome(run)}</p>${run.issue&&html`<small>${run.issue}</small>`}<small>${run.source_name||"Source unavailable"}${run.mode?` · ${String(run.mode).replaceAll("_"," ")}`:""}</small></article>`)}</div></section>`}
      <div class="review-sync"><span>Review data refreshed: ${formatReviewRefresh(data.last_sync)}</span><span>Current ${data.inbox_counts?.current||0} · History ${data.inbox_counts?.history||0} · Incomplete ${data.inbox_counts?.incomplete||0} · Diagnostics ${data.inbox_counts?.development||0}</span><button class="btn ghost" disabled=${loading} onClick=${()=>load(undefined,true)}>Refresh now</button></div>
      ${!data.admission_configured&&html`<div class="review-notice" role="status"><strong>Review decisions are read-only.</strong> ${data.admission_status||"The dedicated admission writer is not configured in this environment."}</div>`}${(data.sync_warnings||[]).map((warning,index)=>html`<div key=${index} class="review-message error" role="alert"><strong>Source sync warning:</strong> ${warning}</div>`)}
      <div class="review-filters" aria-label="Review filters"><label><span>Inbox</span><select value=${filters.inbox} onChange=${e=>{setFilter("inbox",e.target.value);setFilter("source_run_id","");}}><option value="current">Current / latest review</option><option value="history">Previous runs / history</option><option value="actionable">All actionable runs</option><option value="incomplete">Incomplete discovery records</option><option value="development">Development / dry-run diagnostics</option><option value="all">Full audit history</option></select></label><label><span>Status</span><select value=${filters.status} onChange=${e=>setFilter("status",e.target.value)}><option value="pending_review">Pending review</option><option value="approved">Approved</option><option value="rejected_by_reviewer">Rejected</option><option value="all">All</option></select></label><label><span>Entity type</span><select value=${filters.entity_type} onChange=${e=>setFilter("entity_type",e.target.value)}><option value="all">All types</option><option value="actor">Actors</option><option value="person">People</option><option value="event">Events</option></select></label><label><span>Source run</span><select value=${filters.source_run_id} onChange=${e=>setFilter("source_run_id",e.target.value)}><option value="">All runs</option>${data.source_maps.map(map=>html`<option key=${map.source_run_id} value=${map.source_run_id}>${reviewRunLabel(map)}</option>`)}</select></label><label><span>Search</span><input type="search" value=${filters.search} onInput=${e=>setFilter("search",e.target.value)} placeholder="Name or field"/></label></div>
      ${error&&html`<div class="review-message error" role="alert">${error}</div>`}${feedback&&html`<div class="review-message success" role="status">${feedback}</div>`}
      <div class="review-workspace"><div class="review-queue" aria-label="Review candidates"><div class="review-queue-head"><strong>Candidate queue</strong><span>${data.candidates.length} shown</span></div>${loading&&html`<div class="review-empty" role="status">Loading candidates…</div>`}${!loading&&!data.candidates.length&&html`<div class="review-empty">No candidates match.</div>`}${data.candidates.map(candidate=>html`<button key=${candidate.candidate_id} class=${"review-row "+(selectedId===candidate.candidate_id?"active":"")} aria-pressed=${selectedId===candidate.candidate_id} onClick=${()=>setSelectedId(candidate.candidate_id)}><span class="review-row-main"><strong>${candidate.display_name}</strong><small>${candidate.entity_type} · ${reviewRunLabel(candidate)}</small></span><span class=${"review-status "+candidate.status}>${reviewStatusLabel(candidate.status)}</span></button>`)}</div>
      <article class="review-detail" aria-live="polite">${!selected&&html`<div class="review-empty">Select a candidate.</div>`}${selected&&html`<div class="review-detail-head"><div><span class="eyebrow">${selected.entity_type}</span><h2>${selected.display_name}</h2></div><div class="review-badges"><span class=${"review-status "+selected.status}>${reviewStatusLabel(selected.status)}</span><span class=${"duplicate-state "+selected.duplicate_state}>${DUPLICATE_LABELS[selected.duplicate_state]||selected.duplicate_state}</span></div></div>
        ${selected.admission_error&&html`<div class="review-message error"><strong>Last admission failed:</strong> ${selected.admission_error}</div>`}
        ${actorSummary&&html`<section class="review-section review-actor-summary"><h3>Actor classification and location</h3><div class="review-summary-group"><h4>Classification</h4><dl class="review-facts"><div><dt>Actor Category</dt><dd>${actorSummary.actor_category||"Not provided"}</dd></div><div><dt>Category Type</dt><dd>${actorSummary.category_type||"Not yet enriched"}</dd></div></dl>${actorSummary.legacy_category_fallback&&html`<p class="review-compat-note">Actor Category is temporarily shown from the legacy actor_type field. Category Type is not inferred.</p>`}</div><div class="review-summary-group"><h4>Location</h4><dl class="review-facts"><div><dt>City</dt><dd>${actorSummary.city||"Not provided"}</dd></div><div><dt>State</dt><dd>${actorSummary.state||"Not provided"}</dd></div><div><dt>Region</dt><dd>${actorSummary.region||"Not provided"}</dd></div><div><dt>Country</dt><dd>${actorSummary.country||"Not provided"}</dd></div></dl></div></section>`}
        <section class="review-section"><h3>Final record</h3><div class="review-field-grid">${selected.editable_fields.map(field=>fieldControl(html,selected,field,draft[field],edit,!pending||busy,draftErrors[field]))}</div>${pending&&html`<button class="btn ghost" disabled=${busy||Object.keys(draftErrors).length>0} onClick=${save}>Save edits</button>`}</section>
        <section class="review-section"><h3>Evidence</h3>${!selected.evidence.length&&html`<p class="muted">No source links preserved.</p>`}<ul class="review-evidence">${selected.evidence.map((source,index)=>html`<li key=${source.url+index}><a href=${source.url} target="_blank" rel="noreferrer">${source.url}</a>${source.supports&&html`<span>${source.supports}</span>`}</li>`)}</ul></section>
        ${lightFacts.length>0&&html`<section class="review-section"><h3>Light Pull evidence</h3><p class="muted">Topic-scoped facts collected before this actor was parked. “Not found” means the evidence was absent from the pages read; it is not a claim that the fact does not exist.</p><ul class="review-evidence light-pull-facts">${lightFacts.map((fact,index)=>html`<li key=${fact.fact_key+index}><strong>${reviewFieldLabel(fact.fact_key)}</strong><span>${String(fact.collection_state||"not_yet_collected").replaceAll("_"," ")} · confidence ${fact.confidence||"not provided"}${fact.date_read?` · read ${new Date(fact.date_read).toLocaleDateString()}`:""}</span><pre>${formatFactValue(fact.value)}</pre>${fact.source_url&&html`<a href=${fact.source_url} target="_blank" rel="noreferrer">Source</a>`}</li>`)}</ul></section>`}
        ${deepFacts.length>0&&html`<section class="review-section"><h3>Verified Deep Pull evidence</h3><p class="muted">Selected topic-specific facts collected only after a GHUS verification decision.</p><ul class="review-evidence light-pull-facts">${deepFacts.map((fact,index)=>html`<li key=${fact.fact_key+index}><strong>${reviewFieldLabel(fact.fact_key)}</strong><span>${String(fact.collection_state||"not_yet_collected").replaceAll("_"," ")} · confidence ${fact.confidence||"not provided"}${fact.date_read?` · read ${new Date(fact.date_read).toLocaleDateString()}`:""}</span><pre>${formatFactValue(fact.value)}</pre>${fact.source_url&&html`<a href=${fact.source_url} target="_blank" rel="noreferrer">Source</a>`}</li>`)}</ul></section>`}
        ${relationships.length>0&&html`<section class="review-section"><h3>Sourced relationships</h3><ul class="review-evidence">${relationships.map((edge,index)=>html`<li key=${(edge.relationship_type||"")+index}><strong>${edge.relationship_type}</strong><span>${edge.direction} · ${edge.counterpart_type} · ${edge.counterpart_id} · confidence ${edge.confidence||"not provided"}</span>${edge.source_url&&html`<a href=${edge.source_url} target="_blank" rel="noreferrer">${edge.source_url}</a>`}</li>`)}</ul></section>`}
        <section class="review-section"><h3>Top existing matches and differences</h3>${!matches.length&&html`<p class="muted">No existing match was proposed.</p>`}${matches.map(match=>html`<div class="review-match" key=${match.entity_id||match.id}><label><input type="radio" name="target-match" checked=${targetId===(match.entity_id||match.id)} onChange=${()=>setTargetId(match.entity_id||match.id)}/>${match.name||match.display_name||match.entity_id||match.id}</label><table><tbody>${diffFields(draft,match).map(diff=>html`<tr key=${diff.field}><th>${diff.field}</th><td>${String(diff.candidate??"")}</td><td>${String(diff.existing??"")}</td></tr>`)}</tbody></table></div>`)}</section>
        <details class="review-section"><summary>Rubric evidence, score breakdown, qualification, and rerank</summary><pre>${JSON.stringify(selected.agent_metadata,null,2)}</pre></details><details class="review-section"><summary>Complete original discovery payload</summary><pre>${JSON.stringify(selected.original_payload,null,2)}</pre></details>
        <section class="review-section review-decision">
          <div class="review-decision-block"><div class="review-step">1</div><div class="review-step-body"><h3>${selected.entity_type==="actor"?"Actor decision":"Record decision"}</h3><label class="review-field"><span>Decision</span><select value=${decisionKind} disabled=${!pending||busy} onChange=${e=>setDecisionKind(e.target.value)}>${decisionOptions(selected.entity_type).map(option=>html`<option value=${option.value}>${option.label}</option>`)}</select></label>${decisionKind==="same_existing"&&html`<label class="review-field"><span>Existing record ID</span><input value=${targetId} disabled=${!pending||busy} onInput=${e=>setTargetId(e.target.value)} required/></label>`}${decisionKind==="reject"&&html`<div><label class="review-field"><span>Rejection reason</span><select value=${rejectionReason} onChange=${e=>setRejectionReason(e.target.value)}><option value="">Select a reason</option>${REJECTION_REASONS.map(reason=>html`<option value=${reason}>${reason}</option>`)}</select></label>${rejectionReason==="Other"&&html`<label class="review-field"><span>Other reason</span><textarea value=${rejectionOther} onInput=${e=>setRejectionOther(e.target.value)} required></textarea></label>`}</div>`}</div></div>
          ${selected.entity_type==="actor"&&["same_existing","new"].includes(decisionKind)&&html`<div class="review-decision-block"><div class="review-step">2</div><div class="review-step-body"><h3>Hub assignment</h3>
            ${existingMemberships.length>0&&html`<div class="hub-existing"><strong>Existing GHUS membership</strong><p>Preserved historical assignment</p><ul>${existingMemberships.map(hub=>html`<li key=${hub.hub_id||hub.name}><span>${hub.name}</span>${hub.topic_name&&html`<small>${hub.topic_name}</small>`}</li>`)}</ul></div>`}
            ${assignments.length===0&&html`<div class="hub-empty"><strong>No deterministic hub recommendation is available for this candidate yet.</strong><p>The legacy catalog remains available only as a manual fallback.</p><button class="btn ghost" disabled=${!pending||busy||!hubCatalog.length} onClick=${()=>{setManualTopicKey("__fallback__");setHubSearch("");}}>Choose hub manually</button>${!hubCatalog.length&&html`<small>No hub catalog was supplied by the Review API.</small>`}</div>`}
            <div class="hub-assignment-list">${assignments.map(assignment=>html`<article class=${"hub-assignment-card "+assignment.state} key=${assignment.key}><header><div><span class="hub-evidence-label">Topic</span><h4>${assignment.topic_name}</h4></div><span class=${"hub-outcome "+assignment.state}>${assignment.state==="recommended"?"Recommended":assignment.state==="overlap"?"Review needed":assignment.state==="topic_mismatch"?"Topic mismatch":assignment.state==="missing_location"?"Location needed":assignment.state==="outside_radius"?"Outside radius":"No assignment"}</span></header>
              <div class="hub-evidence-grid"><div><span class="hub-evidence-label">Topic match</span><strong>${assignment.topic_match===false?"Not eligible":assignment.hub_topic_name}</strong>${assignment.topic_match===false&&html`<small>Actor topic: ${assignment.topic_name}<br/>Hub topic: ${assignment.hub_topic_name}</small>`}</div>${assignment.state!=="topic_mismatch"&&html`<div><span class="hub-evidence-label">Location match</span><strong>${assignment.state==="missing_location"?"Location unavailable":assignment.distance_miles===null?"Not evaluated":`${assignment.distance_miles} miles from center`}</strong>${assignment.radius_miles!==null&&html`<small>${assignment.radius_miles}-mile radius</small>`}</div>`}</div>
              ${assignment.state==="recommended"&&html`<div class="hub-recommendation"><span>Recommended hub</span><strong>${assignment.recommended_hub_name}</strong><small>${assignment.distance_miles!==null&&assignment.radius_miles!==null?`${assignment.distance_miles} mi / ${assignment.radius_miles} mi · `:""}Nearest qualifying hub supplied by V2</small></div>`}
              ${assignment.state==="overlap"&&html`<div class="hub-review-state"><strong>Multiple qualifying same-topic hubs</strong><p>${assignment.recommended_hub_name} is the V2 recommendation because the backend identified it as the nearest qualifying center.</p><ul class="hub-competitors"><li class="recommended"><span>${assignment.recommended_hub_name}</span><strong>${assignment.distance_miles!==null?`${assignment.distance_miles} mi`:"Distance unavailable"} · Recommended</strong></li>${assignment.competing_hubs.map(hub=>html`<li key=${hub.hub_id||hub.name}><span>${hub.name}</span><strong>${hub.distance_miles!==null?`${hub.distance_miles} mi`:"Distance unavailable"}</strong></li>`)}</ul><small>Issue: hub_radius_overlap</small></div>`}
              ${assignment.state==="outside_radius"&&html`<div class="hub-review-state"><strong>Automatic assignment not recommended</strong><p>${assignment.recommended_hub_name?`Nearest relevant hub: ${assignment.recommended_hub_name}. `:""}${assignment.distance_miles!==null&&assignment.radius_miles!==null?`${assignment.distance_miles} mi / ${assignment.radius_miles} mi. `:""}Outcome: needs_review_location.</p></div>`}
              ${assignment.state==="missing_location"&&html`<div class="hub-review-state"><strong>Hub assignment needs review</strong><p>Topic identified. Location unavailable. Hub assignment cannot be calculated until geography is resolved.</p></div>`}
              ${assignment.state==="topic_mismatch"&&html`<div class="hub-review-state"><strong>Automatic assignment is not permitted</strong><p>Geography is not considered after the controlled topic test fails. Outcome: needs_review_topic.</p></div>`}
              ${assignment.state==="unavailable"&&html`<div class="hub-review-state"><strong>No deterministic assignment</strong><p>No V2 hub outcome was supplied for this topic.</p></div>`}
              <div class="hub-actions">${["recommended","overlap"].includes(assignment.state)&&assignment.recommended_hub_id&&html`<button class="btn" disabled=${!pending||busy} onClick=${()=>chooseHub(assignment.key,assignment.recommended_hub_id,"recommended")}>Accept recommended hub</button>`}<button class="btn ghost" disabled=${!pending||busy} onClick=${()=>leaveHubUnassigned(assignment.key)}>Leave unassigned</button><button class="btn ghost" disabled=${!pending||busy||!hubCatalog.length} onClick=${()=>{setManualTopicKey(assignment.key);setHubSearch("");}}>Choose another hub</button></div>
              ${manualTopicKey===assignment.key&&html`<div class="hub-manual"><label class="review-field"><span>Search hubs</span><input type="search" value=${hubSearch} onInput=${e=>setHubSearch(e.target.value)} placeholder="Search by hub or topic"/></label><label class="review-field"><span>Manual hub exception</span><select value=${hubSelections[assignment.key]?.hub_id||""} onChange=${e=>e.target.value&&chooseHub(assignment.key,e.target.value,"manual")}><option value="">Select a hub</option>${manualHubOptions(hubCatalog,assignment,hubSearch).map(hub=>html`<option value=${hub.hub_id}>${hub.name}${hub.topic_id&&assignment.topic_id&&String(hub.topic_id)!==String(assignment.topic_id)?" — topic mismatch":""}</option>`)}</select></label><small>Manual exceptions preserve the backend hub ID and require reviewer notes.</small></div>`}
            </article>`)}</div>
            ${manualTopicKey==="__fallback__"&&html`<div class="hub-manual"><label class="review-field"><span>Search hubs</span><input type="search" value=${hubSearch} onInput=${e=>setHubSearch(e.target.value)} placeholder="Search by hub or topic"/></label><label class="review-field"><span>Choose hub manually</span><select value=${hubSelections.__fallback__?.hub_id||""} onChange=${e=>e.target.value&&chooseHub("__fallback__",e.target.value,"manual")}><option value="">Select a hub</option>${manualHubOptions(hubCatalog,{},hubSearch).map(hub=>html`<option value=${hub.hub_id}>${hub.name}</option>`)}</select></label><small>This compatibility fallback preserves the selected backend hub ID and requires reviewer notes.</small></div>`}
          </div></div>`}
          ${selected.entity_type==="actor"&&html`<div class="review-decision-block"><div class="review-step">3</div><div class="review-step-body"><h3>New-hub detection</h3>${proposalStatuses.length===0?html`<div class="hub-proposal-state"><strong>No active hub proposal for this actor’s cluster.</strong><p>This actor remains eligible for scheduled cluster analysis.</p></div>`:proposalStatuses.map((proposal,index)=>html`<div class="hub-proposal-state active" key=${proposal.proposal_id||index}><span class="hub-outcome overlap">Potential new hub detected</span><h4>${proposal.name||proposal.proposed_name||"Unnamed hub proposal"}</h4><dl><div><dt>Independent families</dt><dd>${proposal.independent_family_count??"Not supplied"}</dd></div><div><dt>Represented categories</dt><dd>${proposal.independent_category_count??"Not supplied"}</dd></div><div><dt>Cluster radius</dt><dd>${proposal.radius_miles!==undefined?`${proposal.radius_miles} miles`:"Not supplied"}</dd></div><div><dt>Center</dt><dd>${proposal.center_name||proposal.center||"Not supplied"}</dd></div></dl>${proposal.review_url?html`<a class="btn ghost" href=${proposal.review_url}>View hub proposal</a>`:html`<small>Dedicated hub-proposal review link is not available from the current API.</small>`}</div>`)}</div></div>`}
          <div class="review-decision-block"><div class="review-step">${selected.entity_type==="actor"?"4":"2"}</div><div class="review-step-body"><h3>Reviewer and notes</h3><label class="review-field"><span>Reviewer</span><input value=${reviewer} disabled=${!pending||busy} onInput=${e=>setReviewer(e.target.value)} required/></label><label class=${"review-field "+(manualHubOverride&&!String(notes||"").trim()?"invalid":"")}><span>Notes${decisionKind==="defer"?" (why it remains pending)":manualHubOverride?" (required for manual hub exception)":""}</span><textarea value=${notes} disabled=${!pending||busy} onInput=${e=>setNotes(e.target.value)}></textarea>${manualHubOverride&&!String(notes||"").trim()&&html`<small class="field-error">Explain the manual hub exception before committing.</small>`}</label></div></div>
          <div class="review-decision-block review-commit"><div class="review-step">${selected.entity_type==="actor"?"5":"3"}</div><div class="review-step-body"><h3>Commit decision</h3><button class=${"btn "+(decisionKind==="reject"?"danger":"")} disabled=${!canSubmitReview({candidate:selected,reviewer,rejectionReason,rejectionOther,decisionKind,targetId,busy,admissionConfigured:data.admission_configured,draftErrors,manualHubOverride,notes})} onClick=${decide}>${busy?"Committing…":"Commit decision"}</button></div></div>
        </section>`}</article></div></section>`;
  };
}
